- name: Install docker
  ansible.builtin.service:
    name: docker
    enabled: true


- name:  pull the image
  ansible.builtin.shell: docker pull mysql/mysql-server:8.0.28
  args:
    executable: /bin/bash

- name:  pull the image
  ansible.builtin.shell: docker run --name='my_sql_container' -d -p 3306:3306 mysql/mysql-server
  args:
    executable: /bin/bash